# Generated by Django 2.2.2 on 2019-09-28 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 17, 29, 2, 705712), verbose_name='date publishhed'),
        ),
    ]
