# Generated by Django 2.2.2 on 2019-10-12 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191012_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 21, 14, 33, 434818), verbose_name='date publishhed'),
        ),
    ]
