# Generated by Django 2.2.2 on 2019-10-13 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191013_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='turorial_category',
            new_name='tutorial_category',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 15, 47, 21, 5486), verbose_name='date publishhed'),
        ),
    ]
